/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::AssetImage Offsquare;
extern const Sifteo::AssetImage Background;
extern const Sifteo::AssetImage Play;
extern const Sifteo::AssetImage Wait;
extern const Sifteo::AssetImage PlaySustain;
extern const Sifteo::AssetImage Minus;
extern const Sifteo::AssetImage Plus;
extern const Sifteo::AssetImage WaitSustain;
